# Netlify Settings
[build]
  publish = "."
  command = "echo 'Build completed'"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/lot-calculator.html"
  status = 200
