# nixpacks.toml
# Force Railway to detect this as a Python project

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python backend/app.py"
